3 create landing page
Emimint/Allo_Deneigement pull request #101
Opened 2024-02-07 01:52 UTC by f-zahra

![image](https://github.com/Emimint/Allo_Deneigement/assets/109680894/658c7616-ea22-4e1e-8bfd-ad558fc90460)
![image](https://github.com/Emimint/Allo_Deneigement/assets/109680894/53be3319-e7e6-4845-b78a-a14bf0da2be8)

2024-02-08 01:24 UTC, cylia93 approved these changes

2024-02-08 14:03 UTC, Emimint requested changes
@f-zahra on my side it looks the same as the `index.php` page. Could it be you are missing some changes?

2024-02-08 18:30 UTC, f-zahra commented
I have updated the index file so that includes the landing-page file

2024-02-12 03:14 UTC, Emimint approved these changes
Ok

2024-02-12 03:16 UTC, merged