create class administrateur
Emimint/Allo_Deneigement pull request #102
Opened 2024-02-07 22:01 UTC by cylia93

can you check it please

2024-02-07 22:50 UTC, Emimint commented on views/entities/administrateur.php
> +        $this->photo_ur = $photo_ur;
`$this->photo_url`

2024-02-08 13:59 UTC, Emimint requested changes
@cylia93 check the other PRs I made to place this file in the right folder and the additionnal methods we will need.

2024-02-13 02:35 UTC, Emimint approved these changes

2024-02-13 02:36 UTC, f-zahra approved these changes

2024-02-13 02:36 UTC, merged