22 create new user form fournisseur
Emimint/Allo_Deneigement pull request #46
Opened 2024-01-11 22:12 UTC by f-zahra

2024-01-11 22:35 UTC, Emimint requested changes
@f-zahra please have a look at my comment in the head.html.

2024-01-11 22:35 UTC, Emimint commented on src/main/resources/templates/commons/head.html
> +      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
@f-zahra you needs to use the jquery version at line 10: adding a new version might cause some clash later on. It should work just fine without this link :)

2024-01-14 19:53 UTC, Emimint approved these changes
Good!

2024-01-14 19:59 UTC, cylia93 approved these changes

2024-01-14 19:59 UTC, merged